In [3]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
a=np.array(lst)

In [3]:
type(a)

numpy.ndarray

In [4]:
a

array([1, 2, 3, 4, 5])

In [6]:
a.shape

(5,)

In [4]:
a=[1,2,3]
b=[4,5,6]
arr=np.array([a,b])

In [5]:
print(arr.ndim)

2


In [6]:
print(arr.size)

6


In [7]:
print(arr.shape)

(2, 3)


In [12]:
x=np.array([1,2,3])

In [13]:
x=np.append(x,4)
print(x)

[1 2 3 4]


In [14]:
x=np.delete(x,0)
print(x)

[2 3 4]


In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
z=arr.reshape(3,2)
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
arr[0:,1:]

array([[2, 3],
       [5, 6]])

In [19]:
arr[1,1]

5

In [17]:
a=np.arange(0,10,step=2)

In [24]:
a

array([0, 2, 4, 6, 8])

In [18]:
print(a[a<5])

[0 2 4]


In [19]:
print(a.sum())

20


In [20]:
print(np.mean(a))

4.0


In [25]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
a[3:]=100

In [28]:
a

array([  0,   2,   4, 100, 100])

In [33]:
arr1=a
arr1[3:]=500

In [35]:
arr1

array([  0,   2,   4, 500, 500])

In [37]:
a

array([  0,   2,   4, 500, 500])

In [40]:
arr1=a.copy()
print(a)
arr1[3:]=1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [54]:
np.ones(4,dtype=int) #2-d also

array([1, 1, 1, 1])

In [56]:
np.random.rand(2,2)

array([[0.27695121, 0.15642262],
       [0.2541884 , 0.68644083]])

In [58]:
np.random.randn(4,4)

array([[-0.12514692,  0.898658  , -1.10639005,  2.21565262],
       [-0.00898763, -1.09664742,  0.80239482, -1.3770298 ],
       [-0.07196169,  0.0873949 ,  0.87657893,  0.96438283],
       [ 0.63019538,  2.01907755, -0.58382698, -0.14986843]])

In [61]:
np.random.randint(0,100,8)

array([71, 24, 78, 18, 49, 89, 62, 65])

In [63]:
np.random.random_sample((1,5))

array([[0.53139839, 0.26760076, 0.02233886, 0.39087048, 0.25122125]])